### ISSUE TITLE
SMAC in parallel mode and impact of #cores on performance

### ISSUE THREAD

**Issue by ndangtt** [automl/SMAC3#1082]
Hello! When I run SMAC in parallel mode, assuming that I have a fixed budget of 100 trials and that each configuration is fairly expensive to evaluate, would SMAC always utilise all the given #cores, and would there be difference in term of performance (of the best configuration found) if I run the tuning on 36 cores vs 10 cores vs 1 core?

**Comment by benjamc** [comment]
Hi,
SMAC should utilise all given workers.
Probably, there will be a difference in performance because of the order the surrogate model is fitted. Fitting the model in a different order also results in different proposals for configurations. However, we did not benchmark how much the performance would change depending on the number of workers. 
You can specify after how many trials the surrogate model is retrained in the config selector.

**Comment by ndangtt** [comment]
I see, thank you for your reply!
