### ISSUE TITLE
[Question] Anaconda Dependency

### ISSUE THREAD

**Issue by bbudescu** [automl/SMAC3#1163]
What's the reason for which Anaconda is listed as the preferred way to setup SMAC3? I tried running the tests for version `2.2.0` from both a `conda` and regular `venv`, and the same tests seem to fail (ParEGO and mean aggregation from BlackBoxFacade). What are the bad things that happen when one installs `smac` with `pip` in a regular `venv`?

**Comment by eddiebergman** [comment]
Hiyo,

The main reason to use `conda` or any of these distributions is due to a dependency on `random_forest_run` which is a pre-compiled C library with Python bindings. It's one of the top reasons for failures to install on Windows, as we do not ship pre-compiled binaries for windows for that library. We do however ship pre-compiled binaries for Linux, and so on a Linux distribution, this shouldn't matter.

If you are on a Python version which `random_forest_run` is not compiled for, or on a platform that it wasn't compiled for, your best bet is using `conda`, as part of the services they offer from the hosted repositories is that provide compiled versions for you. I.e. they've gone through the trouble of compiling `random_forest_run` on different platforms. You could also try to manually install and compile `random_forest_run` in a typical environment, however you might run into issues with this.

---

All that being said, this issue with `random_forest_run` is a long-standing one and there are better, maintained alternatives that could be used in SMAC. However gauranteeing performance when switching to these other libraries is a difficult procedure which would require a lot of benchmarking and likely to have other unforseen pitfalls.

Lastly, I don't know why the tests fail but it should be largely unrelated to running it in `conda` or otherwise.

**Comment by bbudescu** [comment]
Hi,

Thanks for your answer. Do you think it would make sense to add something about this in the installation docs?

Perhaps something like:

> On linux, you can use `pip`. On windows, you should use `conda`.

**Comment by mwever** [comment]
Hi,

Yes, thank you for this recommendation. We will add a note to the installation docs. I will create an issue for that.

As a side note: We are currently working on replacing this dependency for the already mentioned reasons (#1116). However, as @eddiebergman already pointed out correctly, replacing it requires a lot of benchmarking to guarantee that performance will not degrade. Therefore, it will still take a while until a release.
