### ISSUE TITLE
Cannot easily access the optimization trajectory from python

### ISSUE THREAD

**Issue by mfeurer** [automl/SMAC3#149]
I just tried to access the optimization trajectory of a SMAC run from python. This is the code I've ended up with, and I think we should simplify this drastically by having a trajectory list in the runhistory.

```
with open('traj_aclib2.json') as fh:
        trajectory = fh.read().strip().split('\n')
    import json
    from smac.utils.io.traj_logging import TrajLogger
    trajectory = [json.loads(t) for t in trajectory if len(t) > 0]
    trajectory_configurations = []
    for t in trajectory:
        c = TrajLogger._convert_dict_to_config(
            t['incumbent'], configuration_space)
        if c in trajectory_configurations:
            continue
        trajectory_configurations.append(c)
```

**Comment by mlindauer** [comment]
I completely agree that we should have an internal data structure to keep track of the trajectory. 
However, I don't know why you had to write this code because we already have a function to read a trajectory file from disc:
https://github.com/automl/SMAC3/blob/development/smac/utils/io/traj_logging.py#L158

**Comment by mfeurer** [comment]
Thanks. How could I miss that...
