### ISSUE TITLE
Always save runhistory?

### ISSUE THREAD

**Issue by mfeurer** [automl/SMAC3#204]
At the moment SMAC3 saves the runhistory into its output directory if the shared model mode is activated. In case a user wants to save the runhistory, but his tool (in this case auto-sklearn) can work in both the parallel and the sequential setting, the user has to check whether parallel model is on or not and depending on that write the necessary information to disk. As SMAC2 automatically saved a runs and results file, I wonder whether we should save the runhistory by default as well.

**Comment by mlindauer** [comment]
just my 2 cents: the command line interface of SMAC3 already writes the runhistory to disk by default. The `SMAC` facade doesn't do it because the idea was if the user lives inside the python world, he/she does not want to have unnecessary large files on disk and the runhistory can be a very large file.
