### ISSUE TITLE
# TODO try to calculate an incumbent from the runhistory!

### ISSUE THREAD

**Issue by mlindauer** [automl/SMAC3#212]
https://github.com/automl/SMAC3/blob/master/smac/smbo/smbo.py#L184

This ToDo should be fixed.

**Comment by mfeurer** [comment]
You mean that this TODO should be replaced by code that uses the incumbent calculation from the runhistory?

**Comment by mlindauer** [comment]
Yes, it should probably be replaced by an implementation.
However, I'm not sure under which condition we do not have an incumbent---so, maybe we could delete this simply.

**Comment by shukon** [comment]
From what I'm seeing, the only possibilities in the current scheme to have `self.incumbent = None` are:
- SMBO-object is initialized and `choose_next` is called before `run` (might be done to get challengers from outside the object, since it is not a private function? Not sure if this is realistic - maybe with a combination of customized modules and resumed optimization that reloads old runhistories/warmstart?)
-  `self.initial_design.run` returns `None` in which case we would run into trouble at latest when calling `intensify` with `incumbent=None`

**Comment by mfeurer** [comment]
Regarding your first option, this is exactly what Auto-sklearn does. Auto-sklearn implements the run function itself, thus never calling the run function in the smac package (although this might change at some point).
