### ISSUE TITLE
Change default value in RF example in SMAC3

### ISSUE THREAD

**Issue by mfeurer** [automl/SMAC3#223]
Because 1GB is way too less.

**Comment by mlindauer** [comment]
I already told @shukon to replace this example with a more common example using sklearn.

**Comment by shukon** [comment]
@mlindauer that was merged in https://github.com/automl/SMAC3/pull/195.
I think this is about https://github.com/automl/SMAC3/blob/master/examples/rf.py#L107, which I simply adopted from the old version, because I figured it's supposed to run on most machines or something like that.
@mfeurer What's an appropriate value? 4GB?
It does not affect the optimization if the maximum is more than the actual capacity, does it?

**Comment by mfeurer** [comment]
I think most modern machines have at least 4-6GB of RAM. Assuming that SMAC occupies 1GB itself, and there is maybe an OS, 3GB would be a good default. And a note that this argument is important.

Maybe it would also be good to use a canonical dataset from sklearn, for example the boston housing or the diabetes dataset.
