### ISSUE TITLE
SMAC alters output directory name given by the user

### ISSUE THREAD

**Issue by mfeurer** [automl/SMAC3#240]
The following code changes the output directory name given by the user:

    if self.output_dir:
        self.output_dir += "_run%d" %(run_id)

If the user provides an output directory, I think its name should not be changed.

**Comment by mlindauer** [comment]
What should happen if a user runs SMAC multiple times? In worst case, parallel runs.
The output directories would be overwritten.

**Comment by mfeurer** [comment]
Hm, but it's harder to retrieve in a program if the directory name is changed by SMAC... I'll think about this a little bit more

**Comment by KEggensperger** [comment]
**As discussed offline:**

We introduce a flat folder hierarchy. If the user does not specifie otherwise a SMAC experiment will have the following structure:

`smac_<date>/run_<run_id>/*.json`

The user can specify a output directory, e.g. `./myExperiment` or `./myExperiment/` which results in:

`./myExperiment/run_<run_id>/*.json`

If smac is about to write to an already existing directory, smac will move the folder (without checking whether other processes still use that folder):

`./myExperiment/run_<run_id>/*.json -> ./myExperiment/run_<run_id>.OLD/*.json`

if `run_<run_id>.OLD` already exists, then another `.OLD` is appended (`run_<run_id>.OLD.OLD`)

**Comment by mfeurer** [comment]
@mlindauer @KEggensperger did #334 fix this?

**Comment by mlindauer** [comment]
> @mlindauer @KEggensperger did #334 fix this?

Yes
