### ISSUE TITLE
Documentation does not mention pSMAC

### ISSUE THREAD

**Issue by mfeurer** [automl/SMAC3#251]
explicitly, only the scenario option `shared_mode` without further helpful explanation.

**Comment by shukon** [comment]
That is mainly because I do not know a lot about it. Are there any examples ready? The main idea is multiple SMAC-runs using the same evaluated data, so if exploring the same part of the search-space runs can be skipped? Is [this](http://www.cs.ubc.ca/labs/beta/Projects/SMAC/papers/12-LION-Parallel_AC.pdf) the paper on which it is built (I did not look into it yet)?

**Comment by mfeurer** [comment]
The only example I'm having is how auto-sklearn handles this. @mlindauer should be able to provide you several examples on how to use it for algorithm configuration. 

The feature is not described in a paper yet. Tho only description I'm aware of is the [manual of SMAC2](http://www.cs.ubc.ca/labs/beta/Projects/SMAC/v2.10.03/manual.pdf) on page 8.
