### ISSUE TITLE
Make input_psmac_dirs default to <output_dir>*?

### ISSUE THREAD

**Issue by robintibor** [automl/SMAC3#304]
This is a question/feature request :)

I wondered if one could set the input_psmac_dirs default to <output_dir>* , so that one does not have to keep both parameters in sync and there is less chances of making a mistake when setting these parameters.

E.g.

```
output_dir = /home/schirrmr/data/smac/deterministic
shared_model = 1
```

Would lead automatically to 
```
input_psmac_dirs = /home/schirrmr/data/smac/deterministic*
```
if the user does not set ```input_psmac_dirs``` manually to another value.

For people with issues working diligent and concentrated this would be a big convenience :) :)

**Comment by brenting** [comment]
My version does it slightly different.

The pSMAC algorithm sets as default:
`input_psmac_dirs = output_dir`

However, it writes is run history to:
`<output_dir>/run_<seed>`

So the default value does not find any history. Took me a while to find that out. I now set:
`output_dir = logs/SMAC/`
`shared_model = 1`
`input_psmac_dirs = logs/SMAC/*`

This does work, but it would be nice if this would be the default value.

**Comment by vlavorini** [comment]
Thank you @brenting , I was on the point of opening an issue because I did not figure out how to correctly write `Scenario` options in order to have a pSMAC running.
And at [the example page](https://automl.github.io/SMAC3/stable/psmac.html)  was not clear that also the `output_dir` need to be specified.
