### ISSUE TITLE
Questions about runhistory

### ISSUE THREAD

**Issue by ytsaig** [automl/SMAC3#306]
Thanks for putting together this package (and generally advancing AutoML), it's great!

A couple of questions:
1. Is there a way to obtain information about the posterior distribution and its evolution during the optimization process? For example to produce visualizations similar to the plots in Yelp's MOE (http://yelp.github.io/MOE/demo_tutorial.html)
2. Is there a way to resume training from a given runhistory (if it was interrupted or if we'd like to run more iterations)?

**Comment by mlindauer** [comment]
Dear @ytsaig 

> Is there a way to obtain information about the posterior distribution and its evolution during the optimization process? For example to produce visualizations similar to the plots in Yelp's MOE (http://yelp.github.io/MOE/demo_tutorial.html)

Unfortunately, we do not have such a beautiful visualization such as in MOE. 
Although I really like such visualizations, this might not be feasible for SMAC because we can visualize only one (or at most two) dimensions; however, SMAC is designed to optimize in tens of dimensions. 
Furthermore, we also support categorical variables (/hyperparameters) (not only continuous variables) which are hard to visualize in such a plot.
If you have some ideas how to visualize the evolution of the optimization process over time, we would be very glad.

If you are only interested in the pure numbers (without plots), you could look into the following two packages

* `smac.optimizer.acquisition`
* `smac.epm`

> Is there a way to resume training from a given runhistory (if it was interrupted or if we'd like to run more iterations)?

Right now, we are working on a resume-option; see PR #263. Hopefully, it will be part of the next release.

Best,
Marius

**Comment by ytsaig** [comment]
Thanks @mlindauer for the detailed response. Yes, I was referring to intermediary statistics (numbers). If I manage to put together some useful plots, I'd be happy to submit a PR.

I tried to look at the modules you suggested, but can't see an obvious way to extract statistics. Are there any usage examples in the code (either in SMAC or auto-sklearn) that you recommend I look at?

**Comment by mlindauer** [comment]
> I tried to look at the modules you suggested, but can't see an obvious way to extract statistics

Depends on what you exactly want to do.
Since we haven't planned to add such plots, the code does not provide an easy-to-use interface for such an use-case.

You could look here:
https://github.com/automl/SMAC3/blob/master/smac/optimizer/acquisition.py#L149

For a given X, we predict the mean and variance of the posterior.
At the end of the function, also the EI value is computed. 
So you could create a subclass of `EI` (or any other acquisition function) and add some statistics writer methods.

**Comment by ytsaig** [comment]
Good suggestion, I'll give that a try.
