### ISSUE TITLE
fun optimize (in smac_facade) save stat bug.

### ISSUE THREAD

**Issue by linquanisaac** [automl/SMAC3#338]
The function optimize in smac_facade.py,  the solver save stat would crash when output_dir is None.
```
        try:
            incumbent = self.solver.run()
        finally:
            self.solver.stats.save()   #  should check the self.solver.scenario.output_dir.
            self.solver.stats.print_stats()
            self.logger.info("Final Incumbent: %s" % (self.solver.incumbent))
            self.runhistory = self.solver.runhistory
            self.trajectory = self.solver.intensifier.traj_logger.trajectory
            if self.solver.scenario.output_dir is not None:
                self.solver.runhistory.save_json(
                    fn=os.path.join(self.solver.scenario.output_dir,
                                    "runhistory.json"))
```

**Comment by shukon** [comment]
Hi, thanks for reporting this issue. It is fixed with with #334, which is already merged to [development](https://github.com/automl/SMAC3/tree/development).

The reason for the crash was a [missing check for the existence of an output-dir in stats.py](https://github.com/automl/SMAC3/blob/development/smac/stats/stats.py#L58-L60). This check has now been added.
