### ISSUE TITLE
runcount-limit ignored

### ISSUE THREAD

**Issue by KEggensperger** [automl/SMAC3#40]
The value set for *runcount-limit* in scenario is ignored. It seems like SMAC checks the runcount value only after each *iteration* and not after each target algorithm run, therefore SMAC might do more runs than it is supposed to do.

**Comment by mlindauer** [comment]
This is also the default behavior of SMAC2. Configuration budgets (also time) is only checked after an iteration.
Is this important to fix?

**Comment by KEggensperger** [comment]
No fixing is not important (to me), but we should definitely mention that somewhere.

I am not absolutely sure, but If I remember correctly SMAC2 terminates when `runcount-limit` is reached as it uses eventhandlers to monitor all target algorithm runs and therefore regularly checks termination conditions? At least I couldn't quickly find an example where it uses more runs than specified.

**Comment by mlindauer** [comment]
Since `intensify`is already aware of the stats object, we could also check for an exhausted configuration budget after each iteration in `intensify`. However, I would like to avoid to do it after each target algorithm run since we would not be able to complete a pass through "aggressive racing".

What do you think?

**Comment by mfeurer** [comment]
Since this argument is called `runcount-limit`, it should enforce exactly that. Otherwise a user can select the number of iterations or a runtime limit.

Since the runtime limit has the same enforcement problem, we could also add a flag indicating where the limits are enforced.

**Comment by mlindauer** [comment]
Ok, if we want to enforce an exact `runcount-limit` and a limit on `ta_time_used`, we could do it around the target algorithm. For example, introducing other methods in the abstract `ExecuteTARun` class such as `set_up`: checks whether enough budget is available before a run and modifies the budget accordingly, and `tear_down`: to check after a run whether one of the budget is exhausted.
This solution would also make it easier for users to write new TA subclasses since they don't have to deal with the `stats` object anymore. 

however, I don't know how we want to enforce a strict wall-clock limit.
