### ISSUE TITLE
Feature request: dropout

### ISSUE THREAD

**Issue by vlavorini** [automl/SMAC3#457]
Hello,

   I'm using SMAC3 to optimise a function of 110 parameters, and I see that a lot of iterations are needed. 

Searching the literature, I saw that a version of [dropout](https://www.ijcai.org/proceedings/2017/0291.pdf)  can be useful in cases like mine. In particular, since the function I want to optimise already has a set of parameters which have been manually optimised, and so they are not so bad, choosing at each iteration to leave a fraction of the parameters to the standard values, while exploring the phase space of the others, can be helpful.

I know that the workforce available in your group is limited, so I ask you: is something like this easy to implement in SMAC3, and with easy I mean that a man with limited resources (both in knowledge and in time) can work on it with just some suggestion from your side?

Thank you!

**Comment by mlindauer** [comment]
Dear Vincenco,

Thank you for pointing us to this paper. In fact, we were not aware of this paper.

Please note that there are different cases for optimizing high-dimensional spaces:

1. Only a subset of your parameter space is in fact important but you don't know this subspace. In such a case, I would recommend something along the lines of [rembo](https://ml.informatik.uni-freiburg.de/papers/16-JAIR-REMBO.pdf)
2. If you assume that all your parameters are important, but there is not much interaction between them, you could use dropout (as you suggested).
(3. If you have a high-dimensional space in which all parameters are important and these have strong (unknown) interactions, you have basically lost)

Do you have any intuition which of both cases apply to your application?

Concerning the effort and expert knowledge required to implement dropout in SMAC, it depends a bit on the dropout algorithm: Since we use random forests and not GPs, I would guess that you can modify Algorithm 1 in the dropout paper a bit by optimizing the acquisition function on x^d \union x^D-d. That should be fairly easy to implement because you only have to implement a modified acquisition function optimizer.

**Comment by vlavorini** [comment]
In my case all of the parameters are important, but only a subset of them have big impact. And a (unknown) fraction of them are surely interacting. So probably I'm scarily near your third definition.

Thank you for letting me aware the fact that interacting parameters will limit the functionality of this dropout, I ignored this.

I will both look into rembo, and check if I can follow your suggestion to implement dropout. Let's see what fits best.

Thank you again!

**Comment by mlindauer** [comment]
Hi,

I found a recent paper comparing REMBO and dropout today:
https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=8517011

The conclusion of the authors about dropout was:
`Our results suggest that Dropout should not be favored since it was almost always the worst performing algorithm`

Best regards,
Marius

**Comment by vlavorini** [comment]
Thank you so much! I go check it

**Comment by mlindauer** [comment]
Since this issue is inactive for quite some time, I will close it for now. Please re-open if there any updates.
