### ISSUE TITLE
should smac.utils.dependencies be removed

### ISSUE THREAD

**Issue by KOLANICH** [automl/SMAC3#470]
Is it really needed? IMHO it only causes problems.

**Comment by KEggensperger** [comment]
With this we want to make sure that minimal dependencies are installed before running SMAC. Could you please specify what kind of problems it causes, so we can improve our code?

**Comment by KOLANICH** [comment]
1. The stuff is redundant. pip does it itself. Though it doesn't do it on every run of a library, only on installation, so the possible scenario is when a user installs the package and then uninstalls its dependency or installs an incompatible version, but its users own actions and they shouldn't be checked. If the version is really incompatible, a user will likely get an error. The tool shouldn't prevent a user (of course it doesn't, a user can just patch the tool not to do it, but it's better if a user doesn't have to) from installing any compatible versions or packages the tool is not aware about.

2. It is one of the causes of #469

**Comment by KEggensperger** [comment]
I do understand your concerns and thank you very much for your constructive feedback.

I agree that advanced users should be able to install/uninstall dependencies and/or incompatible versions as they want (and are responsible for any errors). However, from our experience with maintaining software we think that explicitly checking minimal dependencies at runtime significantly lowers the number of issues for the majority of users because the exceptions raised are more descriptive.

Also, I will prepare a PR that implements your proposed solution mentioned in #471 which should hopefully also fix #469.
