### ISSUE TITLE
Can SMAC used to select algorithm ?

### ISSUE THREAD

**Issue by chuchuwen** [automl/SMAC3#480]
Hi, I am new to hyper-parameter tuning,
as I know, SMAC use bayesian optimization to tuning hyper-parameter of algorithm likes SVM,
but if I have several algorithms (e.g., SVM, RandomForest, Neural Networks),
can SMAC (or bayesian optimization) treat these algorithm and their hyper-parameter as a black box to optimize ? (i.e., after SMAC optimization, it can choose the best algorithm and its hyper-parameter)

**Comment by btwewek** [comment]
Will this leads to some algorithms have not been choose during the optimization?

**Comment by mlindauer** [comment]
If you have a very small configuration budget and the number of your algorithms is large, yes that could happen. If your configuration budget is reasonable, the chance is quite high that each algorithm will be chosen at least once, since SMAC also interleaves configurations sampled at random.

**Comment by mfeurer** [comment]
For completeness I would like to point to the recent book on automated machine learning: http://www.automl.org/book/

It describes two systems (Auto-sklearn and Auto-WEKA) which both use SMAC to choose between one of the possible classification algorithms.

I'm closing this for now because the question appears to be answered. Please reopen if not.
