### ISSUE TITLE
Saved Incumbent Format

### ISSUE THREAD

**Issue by mlindauer** [automl/SMAC3#488]
According to the AClib format specifications, we save our trajectory of incumbents such that all parameter values are quoted; so all values are strings. Since we already save our runhistory with the correct types (int, bool, ...) , we should also do it in a further trajectory file such that we can easily read them in.

**Comment by shukon** [comment]
Since this is getting relevant in [CAVE ](https://github.com/automl/CAVE/blob/c9f792f60d25293393c1722d362af43cf2b9b5b1/cave/reader/smac3_reader.py#L96-L106) and PIMP https://github.com/automl/ParameterImportance/issues/107 and also has the milestone 0.11, I'd like to tackle this. The only question for me is:

@mlindauer Should I modify the AClib-procedure or add yet another one? Probably another one to not interfere with cross-package specifications?

**Comment by mlindauer** [comment]
yes, another one would be great. We still have to be compatible with AClib, so we have to be redundant with our files. Thank you for taking care of that!

**Comment by shukon** [comment]
Fixed in #555
