### ISSUE TITLE
Variance prediction across Instances should not take instance hardness distribution into account

### ISSUE THREAD

**Issue by mlindauer** [automl/SMAC3#50]
Right now, our variance prediction marginalized across instances (used for EI) also takes into account the instance hardness distribution (by using the law of total variance). However, as discussed with Stefan and Katha, this is actually wrong here. 
We only want to use the mean of the variance (without the variance of the means).

I will create a PR for this.

**Comment by mfeurer** [comment]
Hi,

I instead of making this fix, we should rather aim to reproduce the way SMAC 1 and 2 compute the variance. We can then still deviate from that procedure if we think the current implementation works better. Here's a short discussion of what I mean:

PR #50 suggests to take the mean of the variances for each instance. The variance for each prediction is computed `variance(means) + mean(variances)`, where `means` and `variances` are the means and variances of the single trees in the forest (see [here](https://bitbucket.org/aadfreiburg/random_forest_run/src/07a76fe8336b1a01126de579a29509d7a3803c77/include/rfr/forests/regression_forest.hpp?at=master&fileviewer=file-view-default#regression_forest.hpp-143)).

In contrast, the paper explains on [page 8](http://aad.informatik.uni-freiburg.de/papers/11-LION5-SMAC.pdf#8)

> finally, we compute means and variances across trees.

which is also implemented in the code of SMAC 1.0.1:

```
/**
 * Gets a prediction for the given configurations and instances
 * @returns a matrix of size Theta.length*2 where index (i,0) is the prediction for Theta[i] 
 * and (i,1) is the variance of that prediction.
 * @see RegtreeFwd.marginalFwd
 */
public static double[][] applyMarginal(RandomForest forest, double[][] Theta, double[][] X) {
    int nTheta = Theta.length;
        
    double[][] treemeans = new double[nTheta][forest.numTrees];
    for (int i=0; i < forest.numTrees; i++) {
        double[] result = RegtreeFwd.marginalFwd(forest.Trees[i], Theta, X);

        for (int j=0; j < nTheta; j++) {
            treemeans[j][i] = result[j];
        }
    }
        
        double[][] retn = new double[nTheta][2]; // mean, var
        for (int i=0; i < nTheta; i++) {
            retn[i][0] = Utils.mean(treemeans[i]);
            retn[i][1] = Utils.var(treemeans[i]);
        }
        return retn;
    }
```

and SMAC 2, see [here](https://bitbucket.org/seramage/fastrf/src/b68439c2c39119db11c60ad0d4cecce067cb2307/src/ca/ubc/cs/beta/models/fastrf/RandomForest.java?at=master&fileviewer=file-view-default#RandomForest.java-885).

The variance calculation would then read:

```
var[i] = 1 / (B - 1) * np.sum([(m - mean[i]) ** 2 for i in range(num_trees)])
```

What do you think of rather implementing it that way?

**Comment by mlindauer** [comment]
Hi,

first of all the official SMAC 2 repo is now here: https://github.com/SJrX/SMAC

As far as I understood your code, you want to marginalize across the instances on each tree and then compute the variance across the trees, right?

I discussed this with Stefan for quite some time on Friday and he convinced me with one argument that this is not what we want: If we increase the number of trees, the variance will go to 0. However, the variance estimate should not directly depend on the number of trees (except from getting more accurate). 

Cheers,
Marius

**Comment by mfeurer** [comment]
Hi,

Thanks for pointing to the right repo. Nevertheless, the code is basically the same as for SMAC 1.0.1.

All in all, I proposed to implement the procedure which was implemented in SMAC 1 & SMAC 2 and not implement a new procedure without comparing it to the old one. The code would do what you summarized, marginalize across instances on each tree and then compute the variance across trees.

After some plotting and discussions with @sfalkner we came to the conclusion that there was some misunderstanding. The standard error of the prediction would go to zero, not the variance. The variance itself would not depend on the number of trees. Nevertheless, the new procedure seems to be more sound (at least in the single instance case) because it takes the  mean of the tree uncertainties and the variance of the tree means into account, while the old procedure will only take the variance between the mean predictions into account. Here are two plots showing the mentioned behaviour:

New procedure:
![total_variances](https://cloud.githubusercontent.com/assets/5320498/18674679/540c3832-7f50-11e6-93cd-8db31b664d46.png)

Old procedure:
![smac](https://cloud.githubusercontent.com/assets/5320498/18674685/586a579c-7f50-11e6-9e89-da57c504e431.png)

Code to reproduce the plots:

```
import smac
import smac.epm
import smac.epm.rf_with_instances
from smac.epm.rf_with_instances import RandomForestWithInstances
import numpy as np
import matplotlib.pyplot as plt

function = lambda x: np.sin(x)
X_values = np.arange(0, 5, 0.01)
plt.plot(X_values, function(X_values))
plt.show()

X = [0.15, 0.2, 0.25, 0.3, 0.5, 0.55, 0.6, 0.7, 1.0, 1.5, 1.6, 2.3, 3.5, 4.0]
oversample = 2.0
for i in range(int(len(X) * oversample) - len(X)):
    x = np.random.choice(X) + np.random.normal(0.0, 0.5)
    X.append(x)
X = np.array(X).reshape((-1, 1))        
    
y = np.array(function(X)).reshape((-1, 1))
types = np.zeros((1, ), dtype=np.uint)

n_trees = 100
rf = RandomForestWithInstances(types=types, num_trees=n_trees, min_samples_split=3, min_samples_leaf=2,
                               do_bootstrapping=False)

rf.train(X, y)
means, vars = rf.predict(X_values.reshape((-1, 1)))
stds = np.sqrt(vars)
plt.plot(X_values, means)
plt.plot(X_values, function(X_values))
plt.fill_between(X_values, (means-stds).flatten(), (means+stds).flatten(), alpha=0.5)
plt.scatter(X, y, marker='x', color='black')
plt.ylim((-2, 2))

means = []
stds = []
for x in X_values:
    x = np.array(x).reshape((-1, ))
    rval = list(map(np.mean, rf.rf.all_leaf_values(x)))
    means.append(np.mean(rval))
    var = 1 / (n_trees + 1) * np.sum([abs(rval[i] - means[-1])**2 for i in range(n_trees)])
    stds.append(np.sqrt(var))
    
means = np.array(means)
stds = np.array(stds)

plt.plot(X_values, means)
plt.plot(X_values, function(X_values))
plt.fill_between(X_values, (means-stds).flatten(), (means+stds).flatten(), alpha=0.5)
plt.scatter(X, y, marker='x', color='black')
plt.ylim((-2, 2))
```
