### ISSUE TITLE
Does smac support multiple objective optimization?

### ISSUE THREAD

**Issue by glard** [automl/SMAC3#507]
`question`  `feature request`

As stated in the title, does smac support multi-objective optimization?

**Comment by mfeurer** [comment]
No, sorry, SMAC does not support this out of the box. With a bit of hacking it's possible, please check for example the unit test `test_facade.test_smac_facade.TestSMACFacade:test_init_EIPS_as_arguments` in the development branch (and the classes used in there) for an example. Instead of accessing runtime, it's also possible to have secondary objective in the additional information and use that to construct the data for your model.

**Comment by glard** [comment]
Thanks, I will have a try

**Comment by glard** [comment]
> No, sorry, SMAC does not support this out of the box. With a bit of hacking it's possible, please check for example the unit test `test_facade.test_smac_facade.TestSMACFacade:test_init_EIPS_as_arguments` in the development branch (and the classes used in there) for an example. Instead of accessing runtime, it's also possible to have secondary objective in the additional information and use that to construct the data for your model.

Thanks, I will have a try

**Comment by mfeurer** [comment]
@renesass can this be closed as it available? 

@glard please see https://automl.github.io/SMAC3/main/details/multi_objective.html

**Comment by dengdifan** [comment]
Solved by https://github.com/automl/SMAC3/pull/816
