### ISSUE TITLE
Bug: Import statement SVM example fails

### ISSUE THREAD

**Issue by rlecover007** [automl/SMAC3#613]
#### Description
Attempted to run the SVM example in the quickstart guide. (https://automl.github.io/SMAC3/stable/quickstart.html)

#### Steps/Code to Reproduce
from smac.facade.smac_facade import SMAC
#### Actual Results
ModuleNotFoundError: No module named 'smac.facade.smac_facade'

#### Versions
 
0.12.0

**Comment by rlecover007** [comment]
from smac.facade.smac_ac_facade import SMAC4AC as SMAC

appears to make things work. 

I also had to add 
iris = datasets.load_iris() to make the code work.

**Comment by mlindauer** [comment]
Thank you for reporting that issue.

In fact, I'm surprised by the link to https://automl.github.io/SMAC3/stable/quickstart.html because that's the docu for version 0.8.0 and not the new one 0.12.0.

The current docu can be found here:
https://automl.github.io/SMAC3/master/quickstart.html
However, I think the import of the lines is also broken. We will fix this soon.

In the meantime, please use this example:
https://automl.github.io/SMAC3/master/examples/SMAC4HPO_svm.html#sphx-glr-examples-smac4hpo-svm-py

> from smac.facade.smac_ac_facade import SMAC4AC as SMAC

Depending on your application, I would not recommend the AC facade, but the HPO facade (`SMAC4HPO`) if you want to use SMAC for hyperparameter optimization.

Best,
Marius

**Comment by rlecover007** [comment]
Thanks for pointing me to a better example. Somehow, in my googling, I ended up with the old documentation and not the current stuff.

**Comment by mfeurer** [comment]
Thanks for reporting this @rlecover007. As a first step, I just deleted the wrong docs from the server. I hope that google will pick up on this change.

**Comment by KEggensperger** [comment]
Closing this, because it is probably fixed and no longer an issue.
