### ISSUE TITLE
Examples in Doc are broken

### ISSUE THREAD

**Issue by mlindauer** [automl/SMAC3#661]
Looking into https://automl.github.io/SMAC3/master/quickstart.html

At least the SVM example is not properly shown anymore. Furthermore, the file ```examples/svm.py```does not exist anymore.

Do we have any Hiwi, who could look into that?

Best,
Marius

**Comment by mfeurer** [comment]
For the person who's going to do this, here's a way to (hopefully) do this in a manner that's future-proof:

1. link to one of the new examples
2. instead of using literal include by line number, use it by text matching (https://sphinx-gallery.github.io/stable/advanced.html#know-your-gallery-files)
3. Add 
    ```
   def setup(app):
       app.warningiserror = True
   ```
   to the file `conf.py` to convert all warnings during documentation building into an error. Now the build should error out when the documentation can no longer be imported.

**Comment by renesass** [comment]
Fixed with the new docs update.
